import './css/globals.css'
import { Inter } from 'next/font/google'
import utilStyles from './css/utils.module.css';
import Image from 'next/image';
import Link from 'next/link';

//components
import Navbar from './components/navbar';



export const metadata = {
  title: 'Music Player',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className='relative overflow-hidden bg-[conic-gradient(at_bottom_right,_var(--tw-gradient-stops))] from-green-200 via-green-400 to-purple-700'>
             <Navbar />
              <main className="flex flex-col items-center justify-center p-24">
                  {children}
              </main>
        </body>
    </html>
  )
}
