version: '3.3'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development

    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres_c
    environment:
      POSTGRES_DB: musicplayer
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes: 
       - ./pgdata:/mnt/app/postgresql/data