version: '3.3'
services: 
  dev:
    container_name: dev
    build:
      context: . #if your Dockerfile is not at the same level change the path here (./frontend)
    restart: always
    command: npx run dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./music:/mnt/app/music
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: postgres_c
    environment:
      POSTGRES_DB: musicplayer
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes: 
       - ./pgdata:/mnt/app/postgresql/data